from __future__ import annotations

import json
import os
import sqlite3
import subprocess
import sys
import urllib.parse
from pathlib import Path

from flask import Flask, Response, jsonify, send_from_directory, url_for
from markupsafe import escape
from dotenv import dotenv_values

SCRIPT_DIR = Path(__file__).resolve().parent  # mcp/db_tools — location of the build scripts
BUILD_SCRIPT = SCRIPT_DIR / "build_db_graph.py"
VISUALIZE_SCRIPT = SCRIPT_DIR / "build_graph_html.py"

_REGISTRY_FILE = Path.home() / ".agent-os" / "active_repos.json"

app = Flask(__name__)

# Shared dark theme for the navigation pages (the graph pages are generated by
# graphify and are not styled here). Plain string, not an f-string — its braces
# are literal CSS.
_PAGE_CSS = """
  :root {
    --bg:#0f1115; --surface:#181b22; --surface-2:#1f232c; --border:#2a2f3a;
    --text:#c9d1d9; --heading:#e6edf3; --muted:#8b949e; --accent:#58a6ff;
  }
  * { box-sizing:border-box; }
  body {
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    background:var(--bg); color:var(--text);
    margin:0 auto; max-width:1040px; padding:48px 32px; line-height:1.55;
  }
  a { color:var(--accent); text-decoration:none; }
  a:hover { text-decoration:underline; }
  h1 { color:var(--heading); font-size:1.55rem; font-weight:600; margin:0 0 6px; letter-spacing:-0.01em; }
  .crumb { font-size:0.85rem; margin-bottom:20px; }
  .crumb a { color:var(--muted); }
  .crumb a:hover { color:var(--accent); }
  .sub { color:var(--muted); font-size:0.85rem; margin:0; word-break:break-all; }
  .lead { color:var(--muted); margin:14px 0 0; }
  hr { border:none; border-top:1px solid var(--border); margin:44px 0 18px; }
  .foot { color:var(--muted); font-size:0.85rem; }
  .foot a { color:var(--muted); }
  .foot a:hover { color:var(--accent); }
  .repos { list-style:none; padding:0; margin:24px 0 0; }
  .repos li { margin:0 0 10px; }
  .repos a.repo {
    display:flex; align-items:baseline; gap:12px; padding:14px 18px;
    background:var(--surface); border:1px solid var(--border); border-radius:10px;
    color:var(--heading); font-weight:500; font-size:1.05rem;
  }
  .repos a.repo:hover { background:var(--surface-2); border-color:#3a414f; text-decoration:none; }
  .repos .path { color:var(--muted); font-weight:400; font-size:0.82rem; }
  .panels { display:flex; gap:18px; margin-top:26px; flex-wrap:wrap; }
  .panel {
    flex:1 1 220px; background:var(--surface); border:1px solid var(--border);
    border-radius:12px; padding:20px 22px;
  }
  .panel h2 {
    color:var(--muted); font-size:0.72rem; font-weight:600; letter-spacing:0.08em;
    text-transform:uppercase; margin:0 0 14px;
  }
  .panel a { display:block; margin:9px 0; font-size:0.94rem; }
  .panel .refresh { margin-top:14px; color:var(--muted); cursor:pointer; font-size:0.88rem; }
  .panel .refresh:hover { color:var(--accent); text-decoration:underline; }
  table { border-collapse:collapse; width:100%; margin-top:22px; font-size:0.92rem; }
  th, td { text-align:left; padding:11px 14px; border-bottom:1px solid var(--border); vertical-align:top; }
  th { color:var(--muted); font-size:0.72rem; font-weight:600; letter-spacing:0.06em; text-transform:uppercase; }
  tbody tr:hover td { background:var(--surface); }
  td code { color:var(--muted); font-size:0.85em; }
  .badge { display:inline-block; padding:2px 10px; border-radius:999px; font-size:0.78rem; font-weight:600; }
  .count { color:var(--muted); font-size:0.85rem; margin-top:16px; }
  .empty { text-align:center; padding:28px; color:var(--muted); }
"""


def _page(title: str, body: str, status: int = 200) -> Response:
    """Wrap body content in the shared dark-themed HTML document.

    `title` and `body` must already be escaped/safe — callers pass escaped slugs.
    """
    html = (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{title}</title>\n"
        f"  <style>{_PAGE_CSS}</style>\n"
        "</head>\n"
        f"<body>\n{body}\n</body>\n</html>"
    )
    return Response(html, status=status, mimetype="text/html")


def _load_registry() -> dict[str, str]:
    """Return {slug: repo_root_str} from the shared registry file."""
    if not _REGISTRY_FILE.exists():
        return {}
    try:
        data = json.loads(_REGISTRY_FILE.read_text())
        return {str(k): str(v) for k, v in data.items() if isinstance(k, str) and isinstance(v, str)}
    except Exception:
        return {}


def _repo_root_for_slug(slug: str) -> Path | None:
    """Resolve a repo root path from the registry. Returns None if not found."""
    path_str = _load_registry().get(slug)
    if not path_str:
        return None
    p = Path(path_str)
    return p if p.exists() else None


def _paths(slug: str) -> tuple[Path | None, Path, Path]:
    """Return (repo_root, db_graph_dir, code_graph_dir) for a slug.

    repo_root is None when the slug is not in the registry.
    """
    repo_root = _repo_root_for_slug(slug)
    if repo_root is None:
        return None, Path(), Path()
    return repo_root, repo_root / ".agent-os" / "db", repo_root / "graphify-out"


def _slug_not_found(slug: str) -> Response:
    slug_esc = escape(slug)
    return _page(
        f"{slug_esc} not found — Agent OS",
        f"<h1>Repository '{slug_esc}' not found</h1>"
        "<p class=\"lead\">This slug is not in the registry. Open a Claude Code session "
        "in the repository to register it.</p>"
        "<hr><p class=\"foot\"><a href='/'>← All repositories</a></p>",
        status=404,
    )


def _missing_file(slug: str, msg: str) -> Response:
    slug_esc = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    return _page(
        f"{slug_esc} — Agent OS",
        f"<h1>{escape(msg)}</h1>"
        f"<hr><p class=\"foot\"><a href='/{slug_u}/'>← Back to {slug_esc}</a></p>",
        status=404,
    )


@app.get("/")
def index():
    registry = _load_registry()
    if not registry:
        body = (
            "<h1>Agent OS</h1>"
            "<p class=\"lead\">No repositories registered yet. Open a Claude Code session "
            "in a repository — the Agent OS plugin registers it automatically.</p>"
        )
    else:
        items = "".join(
            f'<li><a class="repo" href="/{urllib.parse.quote(s, safe="")}/">'
            f'{escape(s)} <span class="path">{escape(p)}</span></a></li>'
            for s, p in sorted(registry.items())
        )
        body = (
            "<h1>Agent OS</h1>"
            "<p class=\"lead\">Active repositories</p>"
            f"<ul class=\"repos\">{items}</ul>"
        )

    body += "<hr><p class=\"foot\"><a href=\"/health\">Health</a></p>"
    return _page("Agent OS Graph Server", body)


@app.get("/<slug>/")
def repo_index(slug: str):
    repo_root = _repo_root_for_slug(slug)
    if repo_root is None:
        return _slug_not_found(slug)

    slug_h = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    root_h = escape(str(repo_root))

    body = f"""  <p class="crumb"><a href="/">← All repositories</a></p>
  <h1>{slug_h}</h1>
  <p class="sub">{root_h}</p>
  <div class="panels">
    <div class="panel">
      <h2>Code Graph</h2>
      <a href="/{slug_u}/code_graph">View graph</a>
      <a href="/{slug_u}/api/code_graph">JSON API</a>
      <a href="/{slug_u}/download/repo/markdown">Download report</a>
      <a class="refresh" onclick="fetch('/{slug_u}/refresh/repo',{{method:'POST'}}).then(r=>r.json()).then(d=>alert(d.status||d.error));return false;">↻ Refresh</a>
    </div>
    <div class="panel">
      <h2>Database Graph</h2>
      <a href="/{slug_u}/db_graph">View graph</a>
      <a href="/{slug_u}/api/db_graph">JSON API</a>
      <a href="/{slug_u}/download/db/graphml">Download GraphML</a>
      <a href="/{slug_u}/download/db/markdown">Download Markdown</a>
      <a class="refresh" onclick="fetch('/{slug_u}/refresh/db',{{method:'POST'}}).then(r=>r.json()).then(d=>alert(d.status||d.error));return false;">↻ Refresh</a>
    </div>
    <div class="panel">
      <h2>Task Cards</h2>
      <a href="/{slug_u}/task_cards">View cards</a>
    </div>
  </div>
  <hr>
  <p class="foot"><a href="/{slug_u}/health">Health check</a></p>"""
    return _page(f"{slug_h} — Agent OS", body)


@app.get("/<slug>/code_graph")
def code_graph(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)
    html_file = code_graph_dir / "graph.html"
    if not html_file.exists():
        return _missing_file(slug, "Code graph not found — refresh via the repo page")
    return send_from_directory(str(code_graph_dir), html_file.name)


@app.get("/<slug>/db_graph")
def db_graph(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)
    html_file = db_graph_dir / "db_graph.html"
    if not html_file.exists():
        return _missing_file(slug, "Database graph not found — refresh via the repo page")
    return send_from_directory(str(db_graph_dir), html_file.name)


@app.get("/<slug>/task_cards")
def task_cards(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)

    db_path = repo_root / ".agent-os" / "cards.sqlite"
    if not db_path.exists():
        return _missing_file(slug, "No task-cards database found in this repository")

    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        cards = conn.execute(
            "SELECT card_id, title, status, priority, created_at, updated_at"
            " FROM cards ORDER BY created_at DESC"
        ).fetchall()
        conn.close()
    except Exception:
        print("task_cards: error reading cards.sqlite", file=sys.stderr)
        return _page(
            "Error — Task Cards",
            "<h1>Error reading cards</h1>"
            "<p class=\"lead\">Could not read the task-cards database.</p>",
            status=500,
        )

    slug_h = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    # (text color, pill background) per status; falls back to muted.
    _status_style = {
        "Created": ("#8b949e", "rgba(139,148,158,0.15)"),
        "In Progress": ("#58a6ff", "rgba(88,166,255,0.15)"),
        "Complete": ("#3fb950", "rgba(63,185,80,0.15)"),
    }
    if not cards:
        rows = "<tr><td colspan='5' class='empty'>No cards yet</td></tr>"
    else:
        rows = ""
        for c in cards:
            fg, bg = _status_style.get(c["status"], ("#8b949e", "rgba(139,148,158,0.15)"))
            rows += (
                f"<tr>"
                f"<td><code>{escape(c['card_id'])[:8]}</code></td>"
                f"<td>{escape(c['title'])}</td>"
                f"<td><span class='badge' style='color:{fg};background:{bg}'>{escape(c['status'])}</span></td>"
                f"<td>{escape(c['priority'] or '')}</td>"
                f"<td class='sub'>{escape(c['updated_at'] or '')[:16]}</td>"
                f"</tr>"
            )

    body = f"""  <p class="crumb"><a href="/{slug_u}/">← Back to {slug_h}</a></p>
  <h1>Task Cards — {slug_h}</h1>
  <table>
    <thead>
      <tr><th>ID</th><th>Title</th><th>Status</th><th>Priority</th><th>Updated</th></tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <p class="count">{len(cards)} card(s)</p>"""
    return _page(f"{slug_h} — Task Cards", body)


@app.get("/<slug>/api/code_graph")
def code_graph_json(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = code_graph_dir / "graph.json"
    if not f.exists():
        return jsonify({"error": "graph.json not found"}), 404
    return send_from_directory(str(code_graph_dir), f.name, mimetype="application/json")


@app.get("/<slug>/api/db_graph")
def db_graph_json(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.json"
    if not f.exists():
        return jsonify({"error": "db_graph.json not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, mimetype="application/json")


@app.get("/<slug>/download/repo/markdown")
def download_repo_markdown(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = code_graph_dir / "GRAPH_REPORT.md"
    if not f.exists():
        return jsonify({"error": "GRAPH_REPORT.md not found"}), 404
    return send_from_directory(str(code_graph_dir), f.name, as_attachment=True, download_name="GRAPH_REPORT.md")


@app.get("/<slug>/download/db/graphml")
def download_db_graphml(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.graphml"
    if not f.exists():
        return jsonify({"error": "db_graph.graphml not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, as_attachment=True, download_name="db_graph.graphml")


@app.get("/<slug>/download/db/markdown")
def download_db_markdown(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.md"
    if not f.exists():
        return jsonify({"error": "db_graph.md not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, as_attachment=True, download_name="db_graph.md")


@app.get("/health")
def health():
    registry = _load_registry()
    return jsonify({"status": "ok", "repos": sorted(registry.keys())})


@app.get("/<slug>/health")
def repo_health(slug: str):
    repo_root, db_graph_dir, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    return jsonify({
        "status": "ok",
        "slug": slug,
        "repo_root": str(repo_root),
        "db_graph": {
            "html_exists": (db_graph_dir / "db_graph.html").exists(),
            "json_exists": (db_graph_dir / "db_graph.json").exists(),
            "graphml_exists": (db_graph_dir / "db_graph.graphml").exists(),
            "markdown_exists": (db_graph_dir / "db_graph.md").exists(),
        },
        "code_graph": {
            "html_exists": (code_graph_dir / "graph.html").exists(),
            "json_exists": (code_graph_dir / "graph.json").exists(),
            "report_exists": (code_graph_dir / "GRAPH_REPORT.md").exists(),
        },
    })


@app.post("/<slug>/refresh/repo")
def refresh_repo(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    try:
        result = subprocess.run(
            ["graphify", "update", ".", "--force"],
            cwd=repo_root, capture_output=True, text=True,
            timeout=300, check=True,
        )
    except FileNotFoundError:
        return jsonify({"error": "graphify not found — install with: pip install graphifyy"}), 500
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Code graph refresh timed out"}), 504
    except subprocess.CalledProcessError as exc:
        return jsonify({"error": "Code graph refresh failed", "stdout": exc.stdout, "stderr": exc.stderr}), 500
    return jsonify({
        "status": "refreshed",
        "graph_type": "code",
        "output": result.stdout.strip(),
        "graph_url": url_for("code_graph", slug=slug),
    })


@app.post("/<slug>/refresh/db")
def refresh_db(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404

    env_vars = dotenv_values(repo_root / ".env")
    db_conn_str = env_vars.get("DB_CONNECTION_STRING") or os.getenv("DB_CONNECTION_STRING")
    if not db_conn_str:
        return jsonify({"error": "DB_CONNECTION_STRING is not set"}), 500
    if not BUILD_SCRIPT.exists() or not VISUALIZE_SCRIPT.exists():
        return jsonify({"error": "build_db_graph.py or build_graph_html.py is missing"}), 500

    env = {**os.environ, "DB_CONNECTION_STRING": db_conn_str}
    try:
        build = subprocess.run(
            [sys.executable, str(BUILD_SCRIPT)],
            cwd=repo_root, capture_output=True, text=True,
            timeout=120, check=True, env=env,
        )
        visualize = subprocess.run(
            [sys.executable, str(VISUALIZE_SCRIPT)],
            cwd=repo_root, capture_output=True, text=True,
            timeout=120, check=True, env=env,
        )
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Database graph refresh timed out"}), 504
    except subprocess.CalledProcessError as exc:
        return jsonify({"error": "Database graph refresh failed", "stdout": exc.stdout, "stderr": exc.stderr}), 500

    return jsonify({
        "status": "refreshed",
        "graph_type": "database",
        "build_output": build.stdout.strip(),
        "visualization_output": visualize.stdout.strip(),
        "graph_url": url_for("db_graph", slug=slug),
    })


if __name__ == "__main__":
    host = "0.0.0.0"
    port = int(os.getenv("PORT", "5000"))
    debug = os.getenv("DEBUG", "false").lower() in {"1", "true", "yes"}
    app.run(host=host, port=port, debug=debug)
