from __future__ import annotations

import json
import os
import sqlite3
import subprocess
import sys
import urllib.parse
from pathlib import Path

from flask import Flask, Response, jsonify, request, send_from_directory, url_for
from markupsafe import escape
from dotenv import dotenv_values

SCRIPT_DIR = Path(__file__).resolve().parent  # mcp/db_tools — location of the build scripts
BUILD_SCRIPT = SCRIPT_DIR / "build_db_graph.py"
VISUALIZE_SCRIPT = SCRIPT_DIR / "build_graph_html.py"

_REGISTRY_FILE = Path.home() / ".agent-os" / "active_repos.json"

app = Flask(__name__)


@app.before_request
def _require_xrw_for_writes():
    """CSRF guard for state-changing requests.

    The refresh endpoints spawn subprocesses, so a forged cross-site POST must
    not be able to trigger them. Requiring a non-simple header
    (``X-Requested-With``) forces a CORS preflight for any cross-origin request,
    which this server never answers permissively — so only same-origin fetch()
    from our own pages (which set the header) is accepted. No authentication is
    added: on the trusted-LAN deployment the bind intentionally stays 0.0.0.0.
    """
    if request.method in ("POST", "PUT", "PATCH", "DELETE"):
        if request.headers.get("X-Requested-With") != "XMLHttpRequest":
            return jsonify({"error": "Missing X-Requested-With header"}), 403


# Shared dark theme for the navigation pages (the graph pages are generated by
# graphify and are not styled here). Plain string, not an f-string — its braces
# are literal CSS.
_PAGE_CSS = """
  :root {
    --bg:#0f1115; --surface:#181b22; --surface-2:#1f232c; --border:#2a2f3a;
    --text:#c9d1d9; --heading:#e6edf3; --muted:#8b949e; --accent:#58a6ff;
  }
  * { box-sizing:border-box; }
  body {
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    background:var(--bg); color:var(--text);
    margin:0 auto; max-width:1040px; padding:48px 32px; line-height:1.55;
  }
  a { color:var(--accent); text-decoration:none; }
  a:hover { text-decoration:underline; }
  h1 { color:var(--heading); font-size:1.55rem; font-weight:600; margin:0 0 6px; letter-spacing:-0.01em; }
  .crumb { font-size:0.85rem; margin-bottom:20px; }
  .crumb a { color:var(--muted); }
  .crumb a:hover { color:var(--accent); }
  .sub { color:var(--muted); font-size:0.85rem; margin:0; word-break:break-all; }
  .lead { color:var(--muted); margin:14px 0 0; }
  hr { border:none; border-top:1px solid var(--border); margin:44px 0 18px; }
  .foot { color:var(--muted); font-size:0.85rem; }
  .foot a { color:var(--muted); }
  .foot a:hover { color:var(--accent); }
  .repos { list-style:none; padding:0; margin:24px 0 0; }
  .repos li { margin:0 0 10px; }
  .repos a.repo {
    display:flex; align-items:baseline; gap:12px; padding:14px 18px;
    background:var(--surface); border:1px solid var(--border); border-radius:10px;
    color:var(--heading); font-weight:500; font-size:1.05rem;
  }
  .repos a.repo:hover { background:var(--surface-2); border-color:#3a414f; text-decoration:none; }
  .repos .path { color:var(--muted); font-weight:400; font-size:0.82rem; }
  .panels { display:flex; gap:18px; margin-top:26px; flex-wrap:wrap; }
  .panel {
    flex:1 1 220px; background:var(--surface); border:1px solid var(--border);
    border-radius:12px; padding:20px 22px;
  }
  .panel h2 {
    color:var(--muted); font-size:0.72rem; font-weight:600; letter-spacing:0.08em;
    text-transform:uppercase; margin:0 0 14px;
  }
  .panel a { display:block; margin:9px 0; font-size:0.94rem; }
  .panel .refresh { margin-top:14px; color:var(--muted); cursor:pointer; font-size:0.88rem; }
  .panel .refresh:hover { color:var(--accent); text-decoration:underline; }
  table { border-collapse:collapse; width:100%; margin-top:22px; font-size:0.92rem; }
  th, td { text-align:left; padding:11px 14px; border-bottom:1px solid var(--border); vertical-align:top; }
  th { color:var(--muted); font-size:0.72rem; font-weight:600; letter-spacing:0.06em; text-transform:uppercase; }
  tbody tr:hover td { background:var(--surface); }
  td code { color:var(--muted); font-size:0.85em; }
  .badge { display:inline-block; padding:2px 10px; border-radius:999px; font-size:0.78rem; font-weight:600; }
  .count { color:var(--muted); font-size:0.85rem; margin-top:16px; }
  .empty { text-align:center; padding:28px; color:var(--muted); }
  tbody tr.clickable { cursor:pointer; }
  .detail-meta { display:flex; gap:18px; flex-wrap:wrap; margin:18px 0 28px; font-size:0.88rem; color:var(--muted); }
  .detail-meta strong { color:var(--text); }
  .detail-section { margin-top:28px; }
  .detail-section h2 { color:var(--muted); font-size:0.72rem; font-weight:600; letter-spacing:0.08em; text-transform:uppercase; margin:0 0 10px; }
  .detail-desc { white-space:pre-wrap; word-break:break-word; background:var(--surface); border:1px solid var(--border); border-radius:8px; padding:16px 18px; font-size:0.9rem; line-height:1.6; }
  .detail-desc.empty { color:var(--muted); font-style:italic; }
  .comment-list { list-style:none; padding:0; margin:0; }
  .comment-list li { border:1px solid var(--border); border-radius:8px; padding:14px 16px; margin-bottom:10px; background:var(--surface); }
  .comment-meta { font-size:0.78rem; color:var(--muted); margin-bottom:6px; }
  .comment-meta strong { color:var(--accent); }
  .comment-body { white-space:pre-wrap; word-break:break-word; font-size:0.88rem; line-height:1.6; }
  /* ── All-cards board ─────────────────────────────────────────── */
  .board-header { display:flex; align-items:baseline; gap:16px; flex-wrap:wrap; margin-bottom:28px; }
  .board-header h1 { margin:0; }
  .board-live { font-size:0.78rem; color:var(--muted); }
  .board-live .dot { display:inline-block; width:7px; height:7px; border-radius:50%; background:var(--accent); margin-right:5px; animation:blink 2s step-end infinite; }
  @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0.25} }
  .board-paused .dot { background:var(--muted); animation:none; }
  .board-wrap { overflow-x:auto; }
  .board { display:grid; grid-template-columns:160px repeat(3,minmax(200px,1fr)); gap:0; margin-top:0; min-width:760px; }
  .board-row { display:contents; }
  .board-cell {
    padding:12px 14px; border-bottom:1px solid var(--border);
  }
  .board-cell:first-child { border-right:1px solid var(--border); }
  .board-head { padding:10px 14px; border-bottom:2px solid var(--border); }
  .board-head:first-child { border-right:1px solid var(--border); }
  .board-head.col-label { font-size:0.72rem; font-weight:600; letter-spacing:0.08em; text-transform:uppercase; color:var(--muted); }
  .board-slug { font-size:0.88rem; font-weight:500; color:var(--heading); word-break:break-all; }
  .board-slug a { color:var(--heading); }
  .board-count { font-size:0.72rem; color:var(--muted); margin-top:2px; }
  .board-other { font-size:0.68rem; color:#d29922; margin-top:2px; }
  .chip-list { list-style:none; padding:0; margin:0; display:flex; flex-direction:column; gap:5px; }
  .chip {
    display:block; padding:5px 9px; border-radius:6px;
    background:var(--surface); border:1px solid var(--border);
    font-size:0.78rem; line-height:1.4; color:var(--text);
    text-decoration:none;
  }
  .chip:hover { border-color:var(--accent); color:var(--heading); text-decoration:none; }
  .chip-title { display:block; font-weight:500; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
  .chip-meta { font-size:0.7rem; color:var(--muted); margin-top:1px; }
  .board-empty { font-size:0.78rem; color:var(--muted); font-style:italic; }
  .board-error { font-size:0.78rem; color:#e3463a; }
"""


# (text color, pill background) per card status; falls back to the Created style.
_STATUS_STYLE: dict[str, tuple[str, str]] = {
    "Created":     ("#8b949e", "rgba(139,148,158,0.15)"),
    "In Progress": ("#58a6ff", "rgba(88,166,255,0.15)"),
    "Complete":    ("#3fb950", "rgba(63,185,80,0.15)"),
}


def _page(title: str, body: str, status: int = 200) -> Response:
    """Wrap body content in the shared dark-themed HTML document.

    `title` and `body` must already be escaped/safe — callers pass escaped slugs.
    """
    html = (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{title}</title>\n"
        f"  <style>{_PAGE_CSS}</style>\n"
        "</head>\n"
        f"<body>\n{body}\n</body>\n</html>"
    )
    return Response(html, status=status, mimetype="text/html")


def _load_registry() -> dict[str, str]:
    """Return {slug: repo_root_str} from the shared registry file."""
    if not _REGISTRY_FILE.exists():
        return {}
    try:
        data = json.loads(_REGISTRY_FILE.read_text())
        return {str(k): str(v) for k, v in data.items() if isinstance(k, str) and isinstance(v, str)}
    except Exception:
        return {}


def _repo_root_for_slug(slug: str) -> Path | None:
    """Resolve a repo root path from the registry. Returns None if not found."""
    path_str = _load_registry().get(slug)
    if not path_str:
        return None
    p = Path(path_str)
    return p if p.exists() else None


def _paths(slug: str) -> tuple[Path | None, Path, Path]:
    """Return (repo_root, db_graph_dir, code_graph_dir) for a slug.

    repo_root is None when the slug is not in the registry.
    """
    repo_root = _repo_root_for_slug(slug)
    if repo_root is None:
        return None, Path(), Path()
    return repo_root, repo_root / ".agent-os" / "db", repo_root / "graphify-out"


def _slug_not_found(slug: str) -> Response:
    slug_esc = escape(slug)
    return _page(
        f"{slug_esc} not found — Agent OS",
        f"<h1>Repository '{slug_esc}' not found</h1>"
        "<p class=\"lead\">This slug is not in the registry. Open a Claude Code session "
        "in the repository to register it.</p>"
        "<hr><p class=\"foot\"><a href='/'>← All repositories</a></p>",
        status=404,
    )


def _missing_file(slug: str, msg: str) -> Response:
    slug_esc = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    return _page(
        f"{slug_esc} — Agent OS",
        f"<h1>{escape(msg)}</h1>"
        f"<hr><p class=\"foot\"><a href='/{slug_u}/'>← Back to {slug_esc}</a></p>",
        status=404,
    )


_CANONICAL_STATUSES = ("Created", "In Progress", "Complete")


def _load_all_cards_data() -> list[dict]:
    """Return per-project card data from every registered repo.

    Shape: [{"slug": str, "counts": {status: int}, "columns": {status: [card, ...]},
             "error": str|None}, ...]

    Each card dict: {"card_id": str, "title": str, "priority": str|None}.
    Projects are sorted by slug. Missing or unreadable cards.sqlite yields
    empty columns (never raises). Non-canonical statuses appear under "Other".
    """
    registry = _load_registry()
    projects = []
    for slug in sorted(registry.keys()):
        root_str = registry[slug]
        db_path = Path(root_str) / ".agent-os" / "cards.sqlite"

        columns: dict[str, list[dict]] = {s: [] for s in _CANONICAL_STATUSES}
        columns["Other"] = []
        counts: dict[str, int] = {s: 0 for s in _CANONICAL_STATUSES}
        counts["Other"] = 0
        error: str | None = None

        if not db_path.exists():
            # Missing DB is not an error — just empty columns.
            pass
        else:
            conn = None
            try:
                conn = sqlite3.connect(str(db_path))
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    "SELECT card_id, title, status, priority"
                    " FROM cards ORDER BY updated_at DESC, created_at DESC"
                ).fetchall()
                for row in rows:
                    status = row["status"]
                    card = {
                        "card_id": row["card_id"],
                        "title": row["title"],
                        "priority": row["priority"],
                    }
                    if status in _CANONICAL_STATUSES:
                        columns[status].append(card)
                        counts[status] += 1
                    else:
                        columns["Other"].append(card)
                        counts["Other"] += 1
            except Exception:
                print(f"_load_all_cards_data: error reading {db_path}", file=sys.stderr)
                error = "Could not read cards database"
                # Reset columns/counts to empty on error
                columns = {s: [] for s in _CANONICAL_STATUSES}
                columns["Other"] = []
                counts = {s: 0 for s in _CANONICAL_STATUSES}
                counts["Other"] = 0
            finally:
                if conn is not None:
                    conn.close()

        projects.append({
            "slug": slug,
            "counts": counts,
            "columns": columns,
            "error": error,
        })
    return projects


@app.get("/all_cards")
def all_cards():
    projects = _load_all_cards_data()

    col_headers = "".join(
        f'<div class="board-head col-label">{escape(s)}</div>'
        for s in _CANONICAL_STATUSES
    )
    header_row = (
        '<div class="board-head" style="color:var(--muted);font-size:0.72rem;">'
        "Project</div>" + col_headers
    )

    rows_html = ""
    for proj in projects:
        slug = proj["slug"]
        slug_h = escape(slug)
        slug_u = urllib.parse.quote(slug, safe="")
        err = proj["error"]

        # Left cell — slug name + total count. Count only canonical-status cards
        # so the number matches the chips rendered in the 3 columns; any
        # non-canonical ("Other") cards are surfaced via a separate small badge
        # rather than silently inflating the count.
        total = sum(proj["counts"][s] for s in _CANONICAL_STATUSES)
        other_n = proj["counts"]["Other"]
        other_badge = f'<div class="board-other">+{other_n} other</div>' if other_n else ""
        slug_cell = (
            f'<div class="board-cell">'
            f'<div class="board-slug"><a href="/{slug_u}/task_cards">{slug_h}</a></div>'
            f'<div class="board-count">{total} card{"s" if total != 1 else ""}</div>'
            f'{other_badge}'
            f"</div>"
        )

        # Column cells
        col_cells = ""
        for status in _CANONICAL_STATUSES:
            if err:
                col_cells += f'<div class="board-cell"><span class="board-error">{escape(err)}</span></div>'
            else:
                cards_in_col = proj["columns"][status]
                if not cards_in_col:
                    col_cells += '<div class="board-cell"><span class="board-empty">—</span></div>'
                else:
                    chips = ""
                    for card in cards_in_col:
                        card_id_u = urllib.parse.quote(card["card_id"], safe="")
                        detail_url = f"/{slug_u}/task_cards/{card_id_u}"
                        priority_h = escape(card["priority"] or "")
                        title_h = escape(card["title"])
                        chips += (
                            f'<a class="chip" href="{detail_url}">'
                            f'<span class="chip-title">{title_h}</span>'
                            f'<span class="chip-meta">{priority_h}</span>'
                            f"</a>"
                        )
                    col_cells += f'<div class="board-cell"><div class="chip-list">{chips}</div></div>'

        # data-slug must match the JSON `proj.slug` so the live-poll JS reconciles
        # these server-rendered rows in place (otherwise the first poll can't match
        # them and duplicates every row).
        rows_html += f'<div class="board-row" data-slug="{slug_h}">{slug_cell}{col_cells}</div>'

    if not projects:
        board_html = (
            '<div class="board-head" style="color:var(--muted)">No repositories registered</div>'
        )
    else:
        board_html = (
            f'<div class="board-wrap">'
            f'<div class="board" id="board-grid">{header_row}{rows_html}</div>'
            f'</div>'
        )

    # Client-side live polling script — all card data is fetched as JSON and
    # rendered via DOM APIs only (no innerHTML with data) to prevent XSS.
    # NOTE: renderBoard() below must mirror the server-rendered board structure
    # above (cell order, classes, the count + "+N other" badge, card/cards
    # pluralization) — the first poll replaces the server DOM with the JS DOM, so
    # any structural change must be made in BOTH places to avoid a visible reshape.
    poll_js = """
<script>
(function () {
  var INTERVAL = 4000;
  var timer = null;
  var paused = false;
  var liveEl = document.getElementById('board-live-status');

  function setPaused(v) {
    paused = v;
    if (liveEl) {
      liveEl.className = v ? 'board-paused' : '';
      liveEl.querySelector('.label').textContent = v ? 'paused' : 'live';
    }
  }

  function buildChip(card, detailUrl) {
    var a = document.createElement('a');
    a.className = 'chip';
    a.href = detailUrl;
    var span1 = document.createElement('span');
    span1.className = 'chip-title';
    span1.textContent = card.title;
    var span2 = document.createElement('span');
    span2.className = 'chip-meta';
    span2.textContent = card.priority || '';
    a.appendChild(span1);
    a.appendChild(span2);
    return a;
  }

  function renderBoard(data) {
    var grid = document.getElementById('board-grid');
    if (!grid) return;
    var projects = data.projects || [];
    var statuses = ['Created', 'In Progress', 'Complete'];

    // Build a map of existing rows by slug for efficient update
    var existingRows = {};
    var rowEls = grid.querySelectorAll('.board-row');
    rowEls.forEach(function (r) { existingRows[r.dataset.slug] = r; });

    // Track which slugs are in new data
    var newSlugs = {};
    projects.forEach(function (proj) { newSlugs[proj.slug] = true; });

    // Remove stale rows
    Object.keys(existingRows).forEach(function (s) {
      if (!newSlugs[s]) grid.removeChild(existingRows[s]);
    });

    projects.forEach(function (proj, idx) {
      var row = existingRows[proj.slug];
      var isNew = !row;
      if (isNew) {
        row = document.createElement('div');
        row.className = 'board-row';
        row.dataset.slug = proj.slug;
      }

      // Rebuild cells
      while (row.firstChild) row.removeChild(row.firstChild);

      // Slug cell
      var slugCell = document.createElement('div');
      slugCell.className = 'board-cell';
      var slugDiv = document.createElement('div');
      slugDiv.className = 'board-slug';
      var slugLink = document.createElement('a');
      slugLink.href = '/' + encodeURIComponent(proj.slug) + '/task_cards';
      slugLink.textContent = proj.slug;
      slugDiv.appendChild(slugLink);
      slugCell.appendChild(slugDiv);
      var total = 0;
      statuses.forEach(function (s) { total += (proj.counts[s] || 0); });
      var countDiv = document.createElement('div');
      countDiv.className = 'board-count';
      countDiv.textContent = total + (total === 1 ? ' card' : ' cards');
      slugCell.appendChild(countDiv);
      var otherN = (proj.counts && proj.counts['Other']) || 0;
      if (otherN) {
        var otherDiv = document.createElement('div');
        otherDiv.className = 'board-other';
        otherDiv.textContent = '+' + otherN + ' other';
        slugCell.appendChild(otherDiv);
      }
      row.appendChild(slugCell);

      // Status column cells
      statuses.forEach(function (status) {
        var cell = document.createElement('div');
        cell.className = 'board-cell';
        if (proj.error) {
          var errSpan = document.createElement('span');
          errSpan.className = 'board-error';
          errSpan.textContent = proj.error;
          cell.appendChild(errSpan);
        } else {
          var cards = (proj.columns && proj.columns[status]) || [];
          if (cards.length === 0) {
            var emptySpan = document.createElement('span');
            emptySpan.className = 'board-empty';
            emptySpan.textContent = '—';
            cell.appendChild(emptySpan);
          } else {
            var chipList = document.createElement('div');
            chipList.className = 'chip-list';
            cards.forEach(function (card) {
              var detailUrl = '/' + encodeURIComponent(proj.slug) +
                              '/task_cards/' + encodeURIComponent(card.card_id);
              chipList.appendChild(buildChip(card, detailUrl));
            });
            cell.appendChild(chipList);
          }
        }
        row.appendChild(cell);
      });

      if (isNew) {
        // Insert in order after any existing header divs and before later project rows
        var allRows = grid.querySelectorAll('.board-row');
        if (allRows.length === 0 || idx >= allRows.length) {
          grid.appendChild(row);
        } else {
          grid.insertBefore(row, allRows[idx]);
        }
      }
    });
  }

  function poll() {
    if (paused) return;
    fetch('/all_cards.json')
      .then(function (r) { return r.json(); })
      .then(renderBoard)
      .catch(function () { /* ignore transient errors */ });
  }

  function startPolling() {
    if (timer) clearInterval(timer);
    timer = setInterval(poll, INTERVAL);
  }

  document.addEventListener('visibilitychange', function () {
    if (document.hidden) {
      setPaused(true);
    } else {
      setPaused(false);
      poll();
      startPolling();
    }
  });

  startPolling();
}());
</script>
"""

    body = (
        '<div class="board-header">'
        '<h1>All Cards</h1>'
        '<span class="board-live" id="board-live-status">'
        '<span class="dot"></span><span class="label">live</span>'
        '</span>'
        "</div>"
        f"{board_html}"
        f"<hr><p class=\"foot\"><a href=\"/\">← All repositories</a></p>"
        f"{poll_js}"
    )
    return _page("All Cards — Agent OS", body)


@app.get("/all_cards.json")
def all_cards_json():
    projects = _load_all_cards_data()
    out = []
    for proj in projects:
        out.append({
            "slug": proj["slug"],
            "counts": proj["counts"],
            "columns": proj["columns"],
            "error": proj["error"],
        })
    return jsonify({"projects": out})


@app.get("/")
def index():
    registry = _load_registry()
    if not registry:
        body = (
            "<h1>Agent OS</h1>"
            "<p class=\"lead\">No repositories registered yet. Open a Claude Code session "
            "in a repository — the Agent OS plugin registers it automatically.</p>"
        )
    else:
        items = "".join(
            f'<li><a class="repo" href="/{urllib.parse.quote(s, safe="")}/">'
            f'{escape(s)} <span class="path">{escape(p)}</span></a></li>'
            for s, p in sorted(registry.items())
        )
        body = (
            "<h1>Agent OS</h1>"
            "<p class=\"lead\">Active repositories</p>"
            f"<ul class=\"repos\">{items}</ul>"
        )

    body += (
        "<hr>"
        "<p class=\"foot\">"
        "<a href=\"/all_cards\">All Cards board</a>"
        " &nbsp;&middot;&nbsp; "
        "<a href=\"/health\">Health</a>"
        "</p>"
    )
    return _page("Agent OS Graph Server", body)


@app.get("/<slug>/")
def repo_index(slug: str):
    repo_root = _repo_root_for_slug(slug)
    if repo_root is None:
        return _slug_not_found(slug)

    slug_h = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    root_h = escape(str(repo_root))

    body = f"""  <p class="crumb"><a href="/">← All repositories</a></p>
  <h1>{slug_h}</h1>
  <p class="sub">{root_h}</p>
  <div class="panels">
    <div class="panel">
      <h2>Code Graph</h2>
      <a href="/{slug_u}/code_graph">View graph</a>
      <a href="/{slug_u}/api/code_graph">JSON API</a>
      <a href="/{slug_u}/download/repo/markdown">Download report</a>
      <a class="refresh" onclick="fetch('/{slug_u}/refresh/repo',{{method:'POST',headers:{{'X-Requested-With':'XMLHttpRequest'}}}}).then(r=>r.json()).then(d=>alert(d.status||d.error));return false;">↻ Refresh</a>
    </div>
    <div class="panel">
      <h2>Database Graph</h2>
      <a href="/{slug_u}/db_graph">View graph</a>
      <a href="/{slug_u}/api/db_graph">JSON API</a>
      <a href="/{slug_u}/download/db/graphml">Download GraphML</a>
      <a href="/{slug_u}/download/db/markdown">Download Markdown</a>
      <a class="refresh" onclick="fetch('/{slug_u}/refresh/db',{{method:'POST',headers:{{'X-Requested-With':'XMLHttpRequest'}}}}).then(r=>r.json()).then(d=>alert(d.status||d.error));return false;">↻ Refresh</a>
    </div>
    <div class="panel">
      <h2>Task Cards</h2>
      <a href="/{slug_u}/task_cards">View cards</a>
    </div>
  </div>
  <hr>
  <p class="foot"><a href="/{slug_u}/health">Health check</a></p>"""
    return _page(f"{slug_h} — Agent OS", body)


@app.get("/<slug>/code_graph")
def code_graph(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)
    html_file = code_graph_dir / "graph.html"
    if not html_file.exists():
        return _missing_file(slug, "Code graph not found — refresh via the repo page")
    return send_from_directory(str(code_graph_dir), html_file.name)


@app.get("/<slug>/db_graph")
def db_graph(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)
    html_file = db_graph_dir / "db_graph.html"
    if not html_file.exists():
        return _missing_file(slug, "Database graph not found — refresh via the repo page")
    return send_from_directory(str(db_graph_dir), html_file.name)


@app.get("/<slug>/task_cards")
def task_cards(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)

    db_path = repo_root / ".agent-os" / "cards.sqlite"
    if not db_path.exists():
        return _missing_file(slug, "No task-cards database found in this repository")

    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        cards = conn.execute(
            "SELECT card_id, title, status, priority, created_at, updated_at"
            " FROM cards ORDER BY created_at DESC"
        ).fetchall()
        conn.close()
    except Exception:
        print("task_cards: error reading cards.sqlite", file=sys.stderr)
        return _page(
            "Error — Task Cards",
            "<h1>Error reading cards</h1>"
            "<p class=\"lead\">Could not read the task-cards database.</p>",
            status=500,
        )

    slug_h = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    if not cards:
        rows = "<tr><td colspan='5' class='empty'>No cards yet</td></tr>"
    else:
        rows = ""
        for c in cards:
            fg, bg = _STATUS_STYLE.get(c["status"], ("#8b949e", "rgba(139,148,158,0.15)"))
            card_id_u = urllib.parse.quote(c["card_id"], safe="")
            detail_url = f"/{slug_u}/task_cards/{card_id_u}"
            # detail_url is fully percent-encoded (quote safe=""), so it cannot
            # contain a quote or angle bracket — safe inside the single-quoted JS
            # string within the double-quoted onclick attribute. Keep that quote
            # nesting (attr=double, JS=single) if editing this line.
            rows += (
                f"<tr class='clickable' onclick=\"location.href='{detail_url}'\">"
                f"<td><code>{escape(c['card_id'])[:8]}</code></td>"
                f"<td><a href='{detail_url}'>{escape(c['title'])}</a></td>"
                f"<td><span class='badge' style='color:{fg};background:{bg}'>{escape(c['status'])}</span></td>"
                f"<td>{escape(c['priority'] or '')}</td>"
                f"<td class='sub'>{escape(c['updated_at'] or '')[:16]}</td>"
                f"</tr>"
            )

    body = f"""  <p class="crumb"><a href="/{slug_u}/">← Back to {slug_h}</a></p>
  <h1>Task Cards — {slug_h}</h1>
  <table>
    <thead>
      <tr><th>ID</th><th>Title</th><th>Status</th><th>Priority</th><th>Updated</th></tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <p class="count">{len(cards)} card(s)</p>"""
    return _page(f"{slug_h} — Task Cards", body)


@app.get("/<slug>/task_cards/<card_id>")
def task_card_detail(slug: str, card_id: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return _slug_not_found(slug)

    db_path = repo_root / ".agent-os" / "cards.sqlite"
    if not db_path.exists():
        return _missing_file(slug, "No task-cards database found in this repository")

    conn = None
    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        card = conn.execute(
            "SELECT card_id, title, description, status, priority, created_at, updated_at"
            " FROM cards WHERE card_id = ?",
            (card_id,),
        ).fetchone()
        if card is None:
            return _missing_file(slug, "Card not found")
        comments = conn.execute(
            "SELECT author, comment, created_at FROM card_comments"
            " WHERE card_id = ? ORDER BY created_at ASC, comment_id ASC",
            (card_id,),
        ).fetchall()
    except Exception:
        print(f"task_card_detail: error reading card {card_id!r}", file=sys.stderr)
        return _page(
            "Error — Task Card",
            "<h1>Error reading card</h1>"
            "<p class=\"lead\">Could not read the task-cards database.</p>",
            status=500,
        )
    finally:
        if conn is not None:
            conn.close()

    slug_h = escape(slug)
    slug_u = urllib.parse.quote(slug, safe="")
    fg, bg = _STATUS_STYLE.get(card["status"], ("#8b949e", "rgba(139,148,158,0.15)"))

    # Description block — preserve whitespace; show placeholder when empty.
    raw_desc = card["description"] or ""
    if raw_desc.strip():
        desc_html = f"<pre class='detail-desc'>{escape(raw_desc)}</pre>"
    else:
        desc_html = "<pre class='detail-desc empty'>No description</pre>"

    # Work log — oldest to newest.
    if comments:
        items = ""
        for cm in comments:
            author_h = escape(cm["author"] or "unknown")
            ts_h = escape(str(cm["created_at"] or "")[:19])
            body_h = escape(cm["comment"] or "")
            items += (
                f"<li>"
                f"<div class='comment-meta'><strong>{author_h}</strong> &mdash; {ts_h}</div>"
                f"<div class='comment-body'>{body_h}</div>"
                f"</li>"
            )
        log_html = f"<ul class='comment-list'>{items}</ul>"
    else:
        log_html = "<p class='sub'>No work log yet.</p>"

    body = (
        f"  <p class='crumb'><a href='/{slug_u}/task_cards'>← Task Cards — {slug_h}</a></p>\n"
        f"  <h1>{escape(card['title'])}</h1>\n"
        f"  <span class='badge' style='color:{fg};background:{bg}'>{escape(card['status'])}</span>\n"
        f"  <div class='detail-meta'>\n"
        f"    <span><strong>Priority</strong> {escape(card['priority'] or '—')}</span>\n"
        f"    <span><strong>Created</strong> {escape(str(card['created_at'] or '')[:19])}</span>\n"
        f"    <span><strong>Updated</strong> {escape(str(card['updated_at'] or '')[:19])}</span>\n"
        f"    <span><strong>ID</strong> <code>{escape(card['card_id'])}</code></span>\n"
        f"  </div>\n"
        f"  <div class='detail-section'>\n"
        f"    <h2>Description</h2>\n"
        f"    {desc_html}\n"
        f"  </div>\n"
        f"  <div class='detail-section'>\n"
        f"    <h2>Work Log</h2>\n"
        f"    {log_html}\n"
        f"  </div>\n"
        f"  <hr><p class='foot'><a href='/{slug_u}/task_cards'>← Back to Task Cards</a></p>"
    )
    return _page(f"{escape(card['title'])} — Task Cards — {slug_h}", body)


@app.get("/<slug>/api/code_graph")
def code_graph_json(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = code_graph_dir / "graph.json"
    if not f.exists():
        return jsonify({"error": "graph.json not found"}), 404
    return send_from_directory(str(code_graph_dir), f.name, mimetype="application/json")


@app.get("/<slug>/api/db_graph")
def db_graph_json(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.json"
    if not f.exists():
        return jsonify({"error": "db_graph.json not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, mimetype="application/json")


@app.get("/<slug>/download/repo/markdown")
def download_repo_markdown(slug: str):
    repo_root, _, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = code_graph_dir / "GRAPH_REPORT.md"
    if not f.exists():
        return jsonify({"error": "GRAPH_REPORT.md not found"}), 404
    return send_from_directory(str(code_graph_dir), f.name, as_attachment=True, download_name="GRAPH_REPORT.md")


@app.get("/<slug>/download/db/graphml")
def download_db_graphml(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.graphml"
    if not f.exists():
        return jsonify({"error": "db_graph.graphml not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, as_attachment=True, download_name="db_graph.graphml")


@app.get("/<slug>/download/db/markdown")
def download_db_markdown(slug: str):
    repo_root, db_graph_dir, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    f = db_graph_dir / "db_graph.md"
    if not f.exists():
        return jsonify({"error": "db_graph.md not found"}), 404
    return send_from_directory(str(db_graph_dir), f.name, as_attachment=True, download_name="db_graph.md")


@app.get("/health")
def health():
    registry = _load_registry()
    return jsonify({"status": "ok", "repos": sorted(registry.keys())})


@app.get("/<slug>/health")
def repo_health(slug: str):
    repo_root, db_graph_dir, code_graph_dir = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    return jsonify({
        "status": "ok",
        "slug": slug,
        "repo_root": str(repo_root),
        "db_graph": {
            "html_exists": (db_graph_dir / "db_graph.html").exists(),
            "json_exists": (db_graph_dir / "db_graph.json").exists(),
            "graphml_exists": (db_graph_dir / "db_graph.graphml").exists(),
            "markdown_exists": (db_graph_dir / "db_graph.md").exists(),
        },
        "code_graph": {
            "html_exists": (code_graph_dir / "graph.html").exists(),
            "json_exists": (code_graph_dir / "graph.json").exists(),
            "report_exists": (code_graph_dir / "GRAPH_REPORT.md").exists(),
        },
    })


@app.post("/<slug>/refresh/repo")
def refresh_repo(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404
    try:
        result = subprocess.run(
            ["graphify", "update", ".", "--force"],
            cwd=repo_root, capture_output=True, text=True,
            timeout=300, check=True,
        )
    except FileNotFoundError:
        return jsonify({"error": "graphify not found — install with: pip install graphifyy"}), 500
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Code graph refresh timed out"}), 504
    except subprocess.CalledProcessError as exc:
        print(f"refresh_repo: graphify failed for {slug!r} (exit {exc.returncode}): {exc.stderr}", file=sys.stderr)
        return jsonify({"error": "Code graph refresh failed — see server logs"}), 500
    return jsonify({
        "status": "refreshed",
        "graph_type": "code",
        "output": result.stdout.strip(),
        "graph_url": url_for("code_graph", slug=slug),
    })


@app.post("/<slug>/refresh/db")
def refresh_db(slug: str):
    repo_root, _, _ = _paths(slug)
    if repo_root is None:
        return jsonify({"error": f"Repo '{slug}' not found"}), 404

    env_vars = dotenv_values(repo_root / ".env")
    db_conn_str = env_vars.get("DB_CONNECTION_STRING") or os.getenv("DB_CONNECTION_STRING")
    if not db_conn_str:
        return jsonify({"error": "DB_CONNECTION_STRING is not set"}), 500
    if not BUILD_SCRIPT.exists() or not VISUALIZE_SCRIPT.exists():
        return jsonify({"error": "build_db_graph.py or build_graph_html.py is missing"}), 500

    env = {**os.environ, "DB_CONNECTION_STRING": db_conn_str}
    try:
        subprocess.run(
            [sys.executable, str(BUILD_SCRIPT)],
            cwd=repo_root, capture_output=True, text=True,
            timeout=120, check=True, env=env,
        )
        subprocess.run(
            [sys.executable, str(VISUALIZE_SCRIPT)],
            cwd=repo_root, capture_output=True, text=True,
            timeout=120, check=True, env=env,
        )
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Database graph refresh timed out"}), 504
    except subprocess.CalledProcessError as exc:
        # Do NOT log or return the subprocess output: build_db_graph.py runs with
        # DB_CONNECTION_STRING in its env and its errors may echo that credential.
        print(f"refresh_db: build failed for {slug!r} (exit {exc.returncode}); "
              f"output withheld (may contain DB credentials)", file=sys.stderr)
        return jsonify({"error": "Database graph refresh failed — re-run the build manually to see details"}), 500

    # Do NOT return build/visualize stdout: those subprocesses run with
    # DB_CONNECTION_STRING in their env and could echo it. The UI only needs the
    # status and the graph URL.
    print(f"refresh_db: rebuilt database graph for {slug!r}", file=sys.stderr)
    return jsonify({
        "status": "refreshed",
        "graph_type": "database",
        "graph_url": url_for("db_graph", slug=slug),
    })


if __name__ == "__main__":
    host = "0.0.0.0"
    port = int(os.getenv("PORT", "5000"))
    debug = os.getenv("DEBUG", "false").lower() in {"1", "true", "yes"}
    app.run(host=host, port=port, debug=debug)
